### ISSUE TITLE
Error on First run

### ISSUE THREAD

**Issue by xitclub** [tinywall/social#1]
I just setup the script and got error on first page

A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 239

**Comment by CaddyDz** [comment]
@xitclub take a look at my pull request. it should solve the problem
all you need to do after that is to set an encryption key

**Comment by Cycle65** [comment]
Hey @CaddyDz 
How can i set the encryption key

**Comment by CaddyDz** [comment]
@Cycle65 
### initialize the Encryption library in your controller using  
```
$this->load->library('encryption');
```
### Generate an encryption key
```
$key = $this->encryption->create_key(16);
```  
**Save your key to your application/config/config.php, open the file and set:**
```
$config['encryption_key'] = 'YOUR KEY';
```

**Comment by Cycle65** [comment]
Hey @CaddyDz 

I really need your help and i also get a job for you...
please how can i get to know you in person...

pls hit me up:
Skype: georgee501
Email: gtulay65@gmail.com
phone:+231888776376/+231770195144

**Comment by Cycle65** [comment]
@CaddyDz 
Hey guy..

can you help me out

A PHP Error was encountered

Severity: Warning

Message: Declaration of Landing::_validateUser() should be compatible with TW_Controller::_validateUser($page)

Filename: controllers/landing.php

Line Number: 3

A PHP Error was encountered

Severity: Notice

Message: Only variables should be assigned by reference

Filename: core/Controller.php

Line Number: 51

An Error Was Encountered
In order to use the Session class you are required to set an encryption key in your config file.

**Comment by CaddyDz** [comment]
@Cycle65 my last PR #4 solves all these errors
